FROM tiangolo/uwsgi-nginx-flask

# Install Certbot
RUN apt-get update && \
    apt-get install -y certbot
    

# Set working directory
WORKDIR /app

# Copy application files
COPY . .

# Expose the HTTP and HTTPS ports
#EXPOSE 80
#EXPOSE 443
EXPOSE 8098

# Install Certbot
RUN apt-get update && \
    apt-get install -y certbot

# Install application dependencies
RUN pip3 install -r requirement.txt

# Run Certbot to obtain the SSL certificate
#RUN certbot certonly --standalone -d rahispathan.com -n --agree-tos --email pathanrahis@gmail.com

# Start the application
CMD ["python", "main.py"]

